language: php
php:
- '7.1'
cache:
  directories:
  - $HOME/.composer/cache/files
services:
- mysql
env:
- SYMFONY_VERSION="3.0.*" DB=mysql
before_script:
- cp app/config/parameters.yml.travis app/config/parameters.yml
- composer install
- php bin/console doctrine:database:create --env=dev
- php bin/console doctrine:schema:create --env=dev
- php bin/console hautelook:fixtures:load --env=dev --quiet
notifications:
  slack:
    secure: hudPbND+/7pUtRKFDoV/1S0GnItezjc3MYEBvH1xJt6LbXD33kC5lL6bOpnyM9boXDlGlbZ3QmYWYAqCCpfWjtMEwwAku9jnU0MqmlxpEQ0zi6j6Ex5aGAQ4Oq3pQ5mh+CfNgSVjXbmDJtDGbcZAUFaG3uVbOAGRdQ096rV8o4wiTyASfR3lp/o3TW0pzH+lk6jxkdEW9YNgr7g5IQkTBKCJuZ7rxhIMJzqvpCTbjV1a6uMFFTuxM3M6YwMuALOvjChUzagZwWPA8rngatgzGBfvD0z2sWqAXiCWSXnTSGLmIZZgcSM4QxXG0nwTDX8wTLOz3kQsLiKqkptGD8v2pmbDIPd66Gj6orOedDbuuA3uFrgqsecXyJEeSxFAwkkReiDIcCHQEjFsnig0ELkmH9vSIvYdsH8AiNzIStjbyX6E3Sj5AM3/AHq+J+mXFpbtsFeBRWD49JRTNuTkXsi8wtp+/vKjaLRL/eZxyUI0e/vSMfZhrfwD7/wLIocnyivpF96bISCAvTpsmcOiGCPbY9/vNVBXeajJg3PHMJ2F+rx/BQcRyMpNDDwMGeKmQYisTiJRFpncC0kY9YtSi+hEPDvMf87LpsAz1gb7YCBdguAcKUihOckD2LVvXgo6JapwMk5qfPE8YDlbBglszmi1kKm1xtPzqFWAJiGIjcrKvwI=
addons:
  sonarcloud:
    organization: frmanager-github
    token:
      secure: uiL7xxxs3uMWJeC4FczTsRuLcB+bvL5wKw9eVN8rJiPAMlHlv2d1f3o+lb9eGWKJZyc33/pGQt7x4YilVGOHOU4dtwjYIFnOYU4l1eopumEbR5hX7Kal5lQo1CKBX7WnQecWeg0Bk/X/nep+S7KmMaDMTzte/74w8KGDrtcUmUqmQI2tzR2+AedA5Muw60hWPn0PgYE/GG+iCspxfnkL+WgChRu9niAM54OTgWnQUiChyOV7N629vokOGJ19ncph9qOZLdvGxYgqsmoXJcG52Hhu+liShKimGvOBPv2q16G7Q2FjIMeIIyLjUtEowYDTVp8UtkpPTeftP7+EUp4cQOpt+9OI++svjxjJJYcdR1BfDI09An1RpRkt2B5yCaZK5Bm2e41zKzgMIgepgRNxGvjEixIpdnglJGqmceWGavig+vZfWycGskd9pEciQUT4VmY5VSg+RJCRl4ETjJYccHPmb0+PynCFOnue3yTGyJZYw2tT4M/WPtIX4sipVeGuMn+JAkkREeqJ0EcCcdsmvmX3Dnz/ZP+682XQinWY/PymD/dqtaRWcsBNEqJA7bZzSq2Qs9Ggy570XA8eoJBh9T09vBNXonGuZUj1TIKNX33kkngVr8wS5+VPx93zSaREf10yI6dFMViooy2QeVcBom3ePbQ/vgkJfqB64G9t3p4=
script:
- phpunit
- sonar-scanner
