app:
    resource: "@AppBundle/Controller/"
    type:     annotation

secure:
    path:     /
    defaults: { _controller: AppBundle:Main:secure }
    schemes:  [https]

api:
    resource: "@AppBundle/Controller/APIController.php"
    prefix:   /api
    type:     annotation

# app/config/routing.yml
